export enum StatusSesi {
  LOBBY = "LOBBY",
  OPEN = "OPEN",
  PAUSED = "PAUSED",
  CLEARED = "CLEARED",
  ARCHIVED = "ARCHIVED",
}

export enum HasilSesi {
  SOLVED = "SOLVED",
  FAILED = "FAILED",
  TIMEOUT = "TIMEOUT",
  ABANDONED = "ABANDONED",
  EXCEPTIONAL = "EXCEPTIONAL",
}

export enum StatusBukti {
  HIDDEN = "HIDDEN",
  DISCOVERED = "DISCOVERED",
  EXAMINED = "EXAMINED",
}

export enum StatusKebenaran {
  TRUE = "TRUE",
  FALSE = "FALSE",
  PARTIAL = "PARTIAL",
  AMBIGUOUS = "AMBIGUOUS",
  UNKNOWN = "UNKNOWN",
}

export enum RelevansiBukti {
  DIRECT = "DIRECT",
  SUPPORTING = "SUPPORTING",
  CONTEXTUAL = "CONTEXTUAL",
  RED_HERRING = "RED_HERRING",
  IRRELEVANT = "IRRELEVANT",
}

export enum RolePemain {
  DETECTIVE = "DETECTIVE",
  SPECTATOR = "SPECTATOR",
}

export enum JenisKejadianDomain {
  PLAYER_JOINED = "PLAYER_JOINED",
  PLAYER_LEFT = "PLAYER_LEFT",
  EVIDENCE_DISCOVERED = "EVIDENCE_DISCOVERED",
  CONTRADICTION_FOUND = "CONTRADICTION_FOUND",
  CONFRONTATION_SUCCESS = "CONFRONTATION_SUCCESS",
  THEORY_UPDATED = "THEORY_UPDATED",
  HINT_USED = "HINT_USED",
  ACCUSATION_PROPOSED = "ACCUSATION_PROPOSED",
  ACCUSATION_QUALIFIED = "ACCUSATION_QUALIFIED",
  FINAL_ACCUSATION = "FINAL_ACCUSATION",
  CASE_CLEARED = "CASE_CLEARED",
  CASE_ARCHIVED = "CASE_ARCHIVED",
  CASE_SESSION_CREATED = "CASE_SESSION_CREATED",
  CASE_STARTED = "CASE_STARTED",
  CASE_PUBLISHED = "CASE_PUBLISHED",
  CASE_DISABLED = "CASE_DISABLED",
  USER_BLOCKED = "USER_BLOCKED",
  GROUP_DISABLED = "GROUP_DISABLED",
  XP_EARNED = "XP_EARNED",
  ACHIEVEMENT_UNLOCKED = "ACHIEVEMENT_UNLOCKED",
}
